### ISSUE TITLE
Craftsense is unusably laggy when enabled [Forge 1.20.1]

### ISSUE THREAD

**Issue by YnwLNE** [dooji2/craftsense#10]
Video example: 

https://github.com/user-attachments/assets/197ebb1d-927d-4647-a274-88e407e4c8bf

**Comment by dooji2** [comment]
I can confirm it indeed is very slow when there are a lot of mods that add new items/blocks, working on a fix now; thanks!

Update: What I just pushed an hour ago is wrong, I'll work on all this tomorrow

**Comment by YnwLNE** [comment]
Thank you for your work!

**Comment by dooji2** [comment]
Alright I just updated CraftSense, please try out v1.1.1 and see if it's better :D

**Comment by dooji2** [comment]
did not mean to close lol my bad

**Comment by CaoTrongThang** [comment]
I'll test the update!

**Comment by CaoTrongThang** [comment]
I think it isn't lagging anymore but I can't pick the item out of the suggestion even tho I've enough crafting materials
![image](https://github.com/user-attachments/assets/b8e486ea-24f9-41e6-973f-de892cddf1ba)

**Comment by dooji2** [comment]
can you try it without any mods on the same modloader/version and see if it still happens? 
works fine for me on forge 1.20.1 w just craftsense, connector and ffapi

I tried a few modpacks yesterday to test performance and one of them had that mod that adds stuff to the crafting table, I believe there is an incompatibility issue with it :<, but maybe I'm wrong - try removing that mod first and see if it still happens, even if it doesn't - pls create a new issue
